package com.example.vhaapp.utils

import android.content.Context
import android.widget.Toast

object Utils {

    fun toast(context: Context, message: String) {
        Toast.makeText(context, message, Toast.LENGTH_SHORT).show()
    }

    fun returnSynonymsList() :List<String> {
        return listOf(
            "Skin Rash",
            "Swollen Gums",
            "Sweating",
            "malaise",
            "receiving unsterile injections",
            "Stuffy Nose",
            "intolerance of light",
            "Intolerence of sound",
            "chills",
            "Gums Bleeding",
            "fever",
            "Loss of Balance",
            "Foul smelling breath",
            "weight loss",
            "Mucus dripping down the throat",
            "Iching",
            "Red Spots",
            "Sneezing",
            "Tooth loss",
            "Space b/w teeth",
            "Frequent mouthsore",
            "lethargy",
            "feel irritable",
            "Bad taste",
            "Tooth ache",
            "Irregular heartbeats",
            "Dry mouth",
            "Thick saliva",
            "Weekend Bones",
            "Sensitivity",
            "delayed wound healing'",
            "internal bleeding",
            "abnormal formation of bones and teeth",
            "Low metabolism",
            "psychological arrears",
            "deaf-muteness",
            "Mentrual Bleeding",
            "Dysmenorrhea",
            "Iregular Bleeding",
            "Trouble in swallowing",
            "unsteadiness",
            "Diarrhea",
            "continuous sneezing",
            "Shiverring",
            "watering from eyes",
            "pain in the pelvis/lower back",
            "Indigestion",
            "Blurred and Distorted vision",
            "Excessive Hunger",
            "Stiff Neck",
            "Depression",
            "inability to stay warm",
            "Visual Disturbance",
            "swelling of the abdomen",
            "Nausa",
            "Contipation",
            "Belly Pain",
            "lack of appetite",
            "Spinning",
            "body aches",
            "Unsteadiness",
            "headache",
            "Pus Filled",
            "Blackheads",
            "Scurring",
            "Facial Pain",
            "mucus in the faeces",
            "Yellowish skin",
            "dark urine",
            "Vaginal irritation",
            "Visible Bulging",
            "Pressure sensation",
            "Urinary leakage",
            "Lower back discomfort",
            "urinary infections",
            "Corkscrew hairs",
            "breathlessness",
            "weight gain",
            "cold hands and feets",
            "mood swings",
            "Soreness in the chest",
            "dizziness",
            "puffy face and eyes",
            "enlarged thyroid",
            "drying and tingling lips",
            "Anxiety",
            "Infertility",
            "Loss of body tissues",
            "apathy",
            "loss of body fat",
            "Sore throat",
            "Irritability",
            "Stomach infection",
            "enlarged liver",
            "thinning of the hair",
            "coarse hair texture",
            "dislodged teeth",
            "dermatitis",
            "distended abdomen",
            "enlarged tummy",
            "Muscle thinning",
            "dry and scaly skin",
            "loose skin",
            "Lower immunity",
            "Mouth sores",
            "shortness of breath",
            "Sunken eyes",
            "pallor",
            "lethargy",
            "tiredness",
            "swollen jaw",
            "puffy cheeks and tender",
            "Increased tear production",
            "Swelling of eyelidds",
            "Constipation",
            "Crusting of eyelids",
            "red colored eye",
            "Burning eye",
            "dehydration",
            "Loss of appetite",
            "Redness around/inside the mouth",
            "Foul smelling breath",
            "Swelling of face",
            "Delayed Growing",
            "Bright red, dusky red or purplish gums",
            "Tender gums",
            "Abdominal cramps",
            "Yellow urine",
            "Yellowing of eyes",
            "Itching",
            "Diarrhoea",
            "Chest Pain",
            "Painful urination",
            "Runny nose",
            "bone fractures",
            "menstrual cramping",
            "skeletal deformities",
            "Bleeding during periods",
            "dental problems",
            "Bowed Legs",
            "Painful chewing",
            "Tooth loss",
            "Pus between your teeth and gums",
            "pits in your teeth",
            "Muscle Ache",
            "Stains",
            "pain around affected teeth",
            "cavities in teeth",
            "loose fillings",
            "food trapped in teeth",
            "difficulty biting  foods",
            "red/blue spots on the skin",
            "Pain in the spine, pelvis and legs",
            "vomitting",
            "Pelvic pressure",
            "Frequent urination",
            "Nausea",
            "Fatigue",
            "scratchy voice",
            "Neck vein swelling",
            "tightness in the throat area",
            "swelling in the front of the neck",
            "coughing",
            "Trouble in breathing")
    }
}